### DISCUSSION TITLE
Is possible add pretty print to a file?

### DISCUSSION THREAD

**Discussion by TeoDev1611** [pelletier/go-toml#705] [Questions] [answered]
Hi 😃 

Your work is amazing but I have a question/idea is possible make a "pretty print" of a file like pass from:

```toml
[foo]
    data1 = { x = 1,   y = 2 }
data2 = {         x = 1, y = 2 }

      [bar]
data1 = { x = 2,     y = 1 }
  data2 = { x = 2,      y = 1 }
```

To a beautifull formatted file like this:
```toml
[foo]
data1 = { x = 1, y = 2 }
data2 = { x = 1, y = 2 }

[bar]
data1 = { x = 2, y = 1 }
data2 = { x = 2, y = 1 }
```

Exists any function or way to make this? Or if this is not avaliable can you add this :)
