### DISCUSSION TITLE
v2.0.3

### DISCUSSION THREAD

**Discussion by pelletier** [pelletier/go-toml#805] [Releases]
This version has compatibility issues with Go <= 1.17. Though go-toml doesn't officially support Go less than 2 versions old, a new version has been released with a backward-compatible fix: https://github.com/pelletier/go-toml/releases/tag/v2.0.5.

### Fixed bugs
* Encode: define and fix newlines behavior when using omitempty  by @pelletier in https://github.com/pelletier/go-toml/pull/798
* Encode: don't inherit omitempty by @pelletier in https://github.com/pelletier/go-toml/pull/803
* Decode: error on array table mismatched type by @pelletier in https://github.com/pelletier/go-toml/pull/804
### Other changes
* build(deps): bump github.com/stretchr/testify from 1.7.2 to 1.8.0 by @dependabot in https://github.com/pelletier/go-toml/pull/793 https://github.com/pelletier/go-toml/pull/794 https://github.com/pelletier/go-toml/pull/795
* Go 1.19 by @pelletier in https://github.com/pelletier/go-toml/pull/802

**Full Changelog**: https://github.com/pelletier/go-toml/compare/v2.0.2...v2.0.3

<hr /><em>This discussion was created from the release <a href='https://github.com/pelletier/go-toml/releases/tag/v2.0.3'>v2.0.3</a>.</em>

**Comment by sagikazarmark** [comment]
Looks like this upgrade broke a few tests in Viper: https://github.com/spf13/viper/pull/1417

Haven't looked closer yet, so I can't say for sure what's the problem.

**Reply by pelletier** [reply]
This release cleans up the newline behavior of the encoder. After a quick look it seems like viper is testing for string equality of the output with a hardcoded string.

Before:

```toml
key = 'value'
list = ['item1', 'item2', 'item3']
[map]
key = 'value'

[nested_map]
[nested_map.map]
key = 'value'
list = ['item1', 'item2', 'item3']


```

After:

```toml
key = 'value'
list = ['item1', 'item2', 'item3']

[map]
key = 'value'

[nested_map]
[nested_map.map]
key = 'value'
list = ['item1', 'item2', 'item3']
```

The new output does not have the extra two new lines at the end, and more consistent spacing between blocks.

Seems like the upgrade is a matter of updating the expected string for the test.
