### ISSUE TITLE
Help with Query

### ISSUE THREAD

**Issue by tgulacsi** [pelletier/go-toml#124]
Hi!

Please help me: how can I select the proxy sections?
'$..proxy' seems not work

```toml
[https://0%2E0%2E0%2E0:]

  [https://0%2E0%2E0%2E0:.rewrite]
    to = ["/letme/Dealer/{1}"]
    r = ["^(/letme)?/Dealer/Dealer/(.*)"]

  [https://0%2E0%2E0%2E0:.log]
    args = ["/data/mai/log/splprn_admin-proxy.log"]

  [https://0%2E0%2E0%2E0:.tls]
    protocols = ["tls1.0","tls1.2"]
    args = ["/../admin/ssl/lnx-dev-kbe.unosoft.local.crt.pem","/../admin/ssl/lnx-dev-kbe.unosoft.local.key.pem"]

  [https://0%2E0%2E0%2E0:.proxy]
    header_upstream = ["-Proxy",""]
    args = ["/","http://localhost:"]
    transparent = ""
    policy = ["least_conn"]
    try_duration = ["10s"]
    max_fails = ["1"]
    fail_timeout = ["9s"]
    without = ["/_macroexpert"]

[http://0%2E0%2E0%2E0:]

  [http://0%2E0%2E0%2E0:.log]
    args = ["/data/mai/log/aodb-proxy.log"]

  [http://0%2E0%2E0%2E0:.proxy]
    max_fails = ["3"]
    fail_timeout = ["1s"]
    without = ["/_macroexpert"]
    header_upstream = ["-Proxy",""]
    args = ["/","unix:/data/ws/aodb.socket"]
    transparent = ""
    policy = ["least_conn"]
    try_duration = ["3s"]

[http://0%2E0%2E0%2E0:4444]

  [http://0%2E0%2E0%2E0:4444.proxy]
    without = ["/metrics/mabisz"]
    header_upstream = ["-Proxy",""]
    args = ["/","http://192.168.3.110:3000"]

  [http://0%2E0%2E0%2E0:4444.log]
    args = ["/data/mai/log/grafana-proxy.log"]
```
