### ISSUE TITLE
comment in struct

### ISSUE THREAD

**Issue by yesnault** [pelletier/go-toml#184]
Hi,

Do you plan to do something like this:

```go
type Postgres struct {
    User     string `comment:"A comment on user"`
    Password string  `comment:"A comment on password"`
}
```
for

```toml
[postgres]
# A comment on user
user = ""
# A comment on password
password = ""
```

Or is there a way  to add comment in output ?

Thks

**Comment by yesnault** [comment]
```go
type TypeC struct {
		my string
	}
	type TypeB struct {
		AttrA string  `toml:"user" comment:"A comment on AttrA"`
		AttrB string  `toml:"password" comment:"A comment on AttrB"`
		AttrC string  `toml:"noComment"`
		My    []TypeC `comment:"a comment on My"`
	}
	type TypeA struct {
		TypeB TypeB `toml:"postgres" comment:"it's a comment on type"`
	}

```

marshall ->

```toml
# postgres it's a comment on type
[postgres]
  noComment = "cvalue"

  # A comment on AttrB
  password = "bvalue"

  # A comment on AttrA
  user = "avalue"

  # a comment on My
  [[postgres.My]]

  # a comment on My
  [[postgres.My]]
```

**Comment by yesnault** [comment]
```go
type TypeC struct {
		My string `comment:"a comment on my on typeC"`
	}
	type TypeB struct {
		AttrA string  `toml:"user" comment:"A comment on AttrA"`
		AttrB string  `toml:"password" comment:"A comment on AttrB with a\n break line"`
		AttrC string  `toml:"noComment"`
		AttrD string  `toml:"isCommented" commented:"true"`
		My    []TypeC `comment:"a comment on My"`
	}
	type TypeA struct {
		TypeB TypeB `toml:"postgres" comment:"it's a comment on type"`
	}

	ta := []TypeC{{My: "Foo"}, {My: "Baar"}}
	config := TypeA{TypeB{AttrA: "avalue", AttrB: "bvalue", AttrC: "cvalue", AttrD: "dvalue", My: ta}}
	result, err := Marshal(config)
```

will returns:

```toml
# it's a comment on type
[postgres]
  # isCommented = "dvalue"
  noComment = "cvalue"

  # A comment on AttrB with a
  # break line
  password = "bvalue"

  # A comment on AttrA
  user = "avalue"

  # a comment on My
  [[postgres.My]]

    # a comment on my on typeC
    My = "Foo"

  [[postgres.My]]

    # a comment on my on typeC
    My = "Baar"
```
