### ISSUE TITLE
Dotted keys support

### ISSUE THREAD

**Issue by pelletier** [pelletier/go-toml#230]
https://github.com/toml-lang/toml/blob/master/versions/en/toml-v0.5.0.md#keys

**Dotted keys** are a sequence of bare or quoted keys joined with a dot. This
allows for grouping similar properties together:

```toml
name = "Orange"
physical.color = "orange"
physical.shape = "round"
site."google.com" = true
```

In JSON land, that would give you the following structure:

```json
{
  "name": "Orange",
  "physical": {
    "color": "orange",
    "shape": "round"
  },
  "site": {
    "google.com": true
  }
}
```

Whitespace around dot-separated parts is ignored, however, best practice is to
not use any extraneous whitespace.

Defining a key multiple times is invalid.

```
# DO NOT DO THIS
name = "Tom"
name = "Pradyun"
```

As long as a key hasn't been directly defined, you may still write to it and
to names within it.

```
a.b.c = 1
a.d = 2
```

```
# THIS IS INVALID
a.b = 1
a.b.c = 2
```
