### ISSUE TITLE
Encoder.SetTagName() doesn't appear to work as expected

### ISSUE THREAD

**Issue by skyzyx** [pelletier/go-toml#351]
**Describe the bug**

I'm doing some stuff around using JSON Schema to validate a TOML file. Data-wise, it works great. There's another Go library which enables me to generate Go structs which match my JSON Schema. It's using `json:"whatever"`, which I need to keep for validating the JSON Schema side.

Using the `toml.NewEncoder()` interface, I tried to use `*Encoder.SetTagName()` to set the tag name to look for to `json` instead of `toml`. When I did that, some values of the tree came back with correct data, while some came back as empty/nil.

**To Reproduce**

```toml
schema_version = 42
team_name = "Example: Team Avatar"
account_aws_services = [
  "cloudfront",
  "cwlogging",
  "lambda",
  "s3",
]

[notifications]
  active = ["Example: Name of New Relic → PagerDuty integration?"]
  passive = [
    "Example: Name of New Relic → Slack integration?",
    "Example: Name of New Relic → Email integration?",
  ]

[services]

  [services.vendor_a]
    nonprod = "aaa"
    prod = "zzz"

  [services.vendor_b]
    cms_account_name = "1234567"
    cms_customer_id = "ZZZ"

[triggers]

  [triggers.slack]
    channel = "#name-of-channel"
    url = "https://example.slack.com/archives/EXAMPLE"

  [triggers.email]
    nonprod = "your-team-nonprod@example.pagerduty.com"
    prod = "your-team-prod@example.pagerduty.com"

  [triggers.pagerduty]

    [triggers.pagerduty.services]
      nonprod = "EXAMPLE"
      prod = "EXAMPLE"

[[apps]]
  service_name = "Appa"
  infrastructure_monitoring = true
  infrastructure_type = "ecs"
  ami_version = "2.10.0"
  aws_services = [
    "alb",
    "ec2",
    "ec2_disk",
    "ec_memcache",
    "ec_redis",
    "ecs",
    "ecs_service_metrics",
    "rds",
  ]

  [apps.tags]
    application = "The value of the \"Application\" tag."
    platform = "The value of the \"Platform\" tag."

  [apps.vendor1]
    business_service = "The value of the \"BusinessService\" tag."
    enable_alerting = false

  [apps.docker]
    registry = "containers.example.com"

    [[apps.docker.images]]
      name = "team-avatar/appa"
      type = "nodejs"

  [[apps.environments]]
    name = "dev"
    ecs_cluster = "my-ecs-cluster-appa-dev"
    ecs_task_name = "my-ecs-cluster-appa"

  [[apps.environments]]
    name = "qa"
    ecs_cluster = "my-ecs-cluster-appa-qa"
    ecs_task_name = "my-ecs-cluster-appa"

  [[apps.environments]]
    name = "prod"
    ecs_cluster = "my-ecs-cluster-appa-prod"
    ecs_task_name = "my-ecs-cluster-appa"
```

```go
package main

var (
	defaultSchemaVersion = int64(42)
)

// generated by "schematyper --out-file=src/model.go --package=main --root-type=Config --prefix=Config --ptr-for-omit schema/compiled-schema.json" -- DO NOT EDIT

type Config struct {
	SchemaVersion      int64                `json:"schema_version"`
	TeamName           string               `json:"team_name"`
	AccountAwsServices []string             `json:"account_aws_services"`
	Notifications      ConfigNotifications  `json:"notifications"`
	Services           ConfigConfigServices `json:"services"`
	Triggers           ConfigTriggers       `json:"triggers"`
	Apps               []ConfigApp          `json:"apps"`
}

type ConfigApp struct {
	ServiceName              string              `json:"service_name"`
	InfrastructureMonitoring bool                `json:"infrastructure_monitoring"`
	InfrastructureType       string              `json:"infrastructure_type,omitempty"`
	AmiVersion               string              `json:"ami_version,omitempty"`
	AwsServices              []string            `json:"aws_services,omitempty"`
	Tags                     *ConfigTags         `json:"tags,omitempty"`
	VendorB                  *ConfigAppVendorB   `json:"vendor_b,omitempty"`
	Docker                   *ConfigDocker       `json:"docker,omitempty"`
	Environments             []ConfigEnvironment `json:"environments,omitempty"`
}

type ConfigAppVendorB struct {
	BusinessService string `json:"business_service"`
	EnableAlerting  bool   `json:"enable_alerting"`
}

type ConfigConfigServices struct {
	VendorA ConfigVendorA `json:"vendor_a"`
	VendorB ConfigVendorB `json:"vendor_b"`
}

type ConfigDocker struct {
	Registry string        `json:"registry"`
	Images   []ConfigImage `json:"images"`
}

type ConfigEmail struct {
	Nonprod string `json:"nonprod"`
	Prod    string `json:"prod"`
}

type ConfigEnvironment struct {
	Name        string            `json:"name"`
	EcsCluster  string            `json:"ecs_cluster"`
	EcsTaskName string            `json:"ecs_task_name"`
	Thresholds  *ConfigThresholds `json:"thresholds,omitempty"`
}

type ConfigImage struct {
	Name string `json:"name"`
	Type string `json:"type"`
}

type ConfigNotifications struct {
	Active  []string `json:"active"`
	Passive []string `json:"passive"`
}

type ConfigPagerduty struct {
	Services ConfigPagerdutyServices `json:"services"`
}

type ConfigPagerdutyServices struct {
	Nonprod string `json:"nonprod"`
	Prod    string `json:"prod"`
}

type ConfigSlack struct {
	Channel string `json:"channel"`
	URL     string `json:"url"`
}

type ConfigTags struct {
	Application string `json:"application"`
	Platform    string `json:"platform"`
}

type ConfigTriggers struct {
	Slack     ConfigSlack     `json:"slack"`
	Email     ConfigEmail     `json:"email"`
	Pagerduty ConfigPagerduty `json:"pagerduty"`
}

type ConfigVendorA struct {
	Nonprod string `json:"nonprod"`
	Prod    string `json:"prod"`
}

type ConfigVendorB struct {
	CmsAccountName string `json:"cms_account_name"`
	CmsCustomerID  string `json:"cms_customer_id"`
}
```

And here are the relevant parts of my code.

```go
package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"log"
	"os"

	toml "github.com/pelletier/go-toml"
)

var (
	ConfigFile = fmt.Sprintf("%s/configuration.toml", os.Getenv("PWD"))
)

func main() {
	// Read the file from disk
	raw, err := ioutil.ReadFile(ConfigFile)
	if err != nil {
		log.Fatalln(err)
	}

	// Instantiate our top-level struct
	config := Config{}

	// Load
	tree, err := toml.Load(string(raw))
	if err != nil {
		log.Fatalln(err)
	}

	// Unmarshal into the struct
	err = tree.Unmarshal(&config)
	if err != nil {
		log.Fatalln(err)
	}

	var buf bytes.Buffer
	encoder := toml.NewEncoder(buf).
		ArraysWithOneElementPerLine(true).
		Order(toml.OrderPreserve).
		SetTagName("json")

	err := encoder.Encode(config)
	if err != nil {
		log.Fatalln(err)
	}

	fmt.Println(string(buf.Bytes()))
}
```

**Expected behavior**

Every TOML node which has a value in the original TOML file should have the same value when the final version of the TOML is written to stdout.

**Versions**
 - go-toml: v1.6.0
 - go: 1.14.1
 - operating system: e.g. macOS 10.15, Alpine Linux 3.11.
