### ISSUE TITLE
tree.Get() and tree.GetPath() do not support arrays

### ISSUE THREAD

**Issue by skyzyx** [pelletier/go-toml#352]
**Describe the bug**

Using `tree.Get()` or `tree.GetPath()`, I cannot access the values of TOML arrays.

**To Reproduce**

```toml
schema_version = 42
team_name = "Example: Team Avatar"
account_aws_services = [
  "cloudfront",
  "cwlogging",
  "lambda",
  "s3",
]

[notifications]
  active = ["Example: Name of New Relic → PagerDuty integration?"]
  passive = [
    "Example: Name of New Relic → Slack integration?",
    "Example: Name of New Relic → Email integration?",
  ]

[services]

  [services.vendor_a]
    nonprod = "aaa"
    prod = "zzz"

  [services.vendor_b]
    cms_account_name = "1234567"
    cms_customer_id = "ZZZ"

[triggers]

  [triggers.slack]
    channel = "#name-of-channel"
    url = "https://example.slack.com/archives/EXAMPLE"

  [triggers.email]
    nonprod = "your-team-nonprod@example.pagerduty.com"
    prod = "your-team-prod@example.pagerduty.com"

  [triggers.pagerduty]

    [triggers.pagerduty.services]
      nonprod = "EXAMPLE"
      prod = "EXAMPLE"

[[apps]]
  service_name = "Appa"
  infrastructure_monitoring = true
  infrastructure_type = "ecs"
  ami_version = "2.10.0"
  aws_services = [
    "alb",
    "ec2",
    "ec2_disk",
    "ec_memcache",
    "ec_redis",
    "ecs",
    "ecs_service_metrics",
    "rds",
  ]

  [apps.tags]
    application = "The value of the \"Application\" tag."
    platform = "The value of the \"Platform\" tag."

  [apps.vendor1]
    business_service = "The value of the \"BusinessService\" tag."
    enable_alerting = false

  [apps.docker]
    registry = "containers.example.com"

    [[apps.docker.images]]
      name = "team-avatar/appa"
      type = "nodejs"

  [[apps.environments]]
    name = "dev"
    ecs_cluster = "my-ecs-cluster-appa-dev"
    ecs_task_name = "my-ecs-cluster-appa"

  [[apps.environments]]
    name = "qa"
    ecs_cluster = "my-ecs-cluster-appa-qa"
    ecs_task_name = "my-ecs-cluster-appa"

  [[apps.environments]]
    name = "prod"
    ecs_cluster = "my-ecs-cluster-appa-prod"
    ecs_task_name = "my-ecs-cluster-appa"
```

If I want to get the dev environment for the first app, I would expect to do something like:

```
apps.0.environments.0.name
<nil>
apps[0].environments[0].name
<nil>
```

And if I skip the array indexes, it just gives me the very last thing it can find.

```
apps.environments.name
prod
```

**Expected behavior**

I expect to be able to use the `tree.Get()` or `tree.GetPath()` methods to retrieve the correct values from inside of TOML arrays.

**Versions**
 - go-toml: v1.6.0
 - go: 1.14.1
 - operating system: e.g. macOS 10.15, Alpine Linux 3.11.
