### ISSUE TITLE
Have a way to remove quotes from keys when generating tomls

### ISSUE THREAD

**Issue by franciscodua** [pelletier/go-toml#411]
**Is your feature request related to a problem? Please describe.**
After the latest [release](https://github.com/pelletier/go-toml/releases/tag/v1.8.0), the generated TOML files changed because keys now have quotes. Probably due to [this](https://github.com/pelletier/go-toml/commit/19eb8cf036efc1af977cc37c8b591211bc500d53).

I'm creating configuration files for go revive and where we previously had
```toml
[rule.add-constant]

  [[rule.add-constant.arguments]]
    allowFloats = "0.0,4.0,5.0"
```
we now have:
```toml
["rule.add-constant"]

  [["rule.add-constant".arguments]]
    allowFloats = "0.0,4.0,5.0"
```

This means the generated tomls are no longer valid for go revive (my particular use case).

**Describe the solution you'd like**
For my use case, I would say that one of these:
1. Consider dots (.) as part of the `quoteKeyIfNeeded` function, 
2. Have some way to avoid using quotation marks

Cheers
