### ISSUE TITLE
Various issues with quotation marks in keys

### ISSUE THREAD

**Issue by sclevine** [pelletier/go-toml#427]
### Decoding

It's currently not possible to decode TOML that contains double-quote marks within quoted string keys.
This should work, as quoted keys may contain any valid TOML string: https://toml.io/en/v1.0.0-rc.1#keys

Example, with comparison to github.com/BurntSushi/toml: https://play.golang.org/p/VNjURuifLsC

**Observed output:**
```
panic: (4, 1): invalid key: invalid bare key character: "
```

**Expected output:**
```
map[string]interface {}{"\"a\"":1, "\"b\"":2}
```
for both packages.

### Encoding

Quoted string keys should be equivalent to bare keys with the same contents. Additionally, setting quoted strings with double-quotes inside of them should work properly.

Example via `*Tree.SetPath`: https://play.golang.org/p/3hMSws8UNED

**Observed output:**:
```toml
test = "value3"
test = "value3"
"test2" = "value4"
test2 = "value5"
```

**Expected output:**: 
```toml
# '"test"' = "value1" ## EDIT: ignore this, was a typo
test = "value3" # quoted key also okay
test2 = "value5" # quoted key also okay
``` 

**Versions**
 - go-toml: 34de94e6a887dcd421ab7586d76d26ee5ab3d96a
 - go: 1.14.5
 - operating system: macOS, play.golang.org
