### ISSUE TITLE
Unmarshalling a map of structs does not assign values to the struct's fields

### ISSUE THREAD

**Issue by ewen-lbh** [pelletier/go-toml#429]
**Describe the bug**
When unmarshalling a `map[string]SomeStruct`, the map is correctly parsed, but all of the `SomeStruct` fields have their zero/initialization values (`""` for `string`, etc)

**To Reproduce**
toml file:
```toml
[materialfox]
repository = "https://github.com/muckSponge/MaterialFox"
files = { all = ["chrome/**"] }
[materialfox.config]
"toolkit.legacyUserProfileCustomizations.stylesheets" = true
"svg.context-properties.content.enabled" = true
"browser.tabs.tabClipWidth" = 83
"materialFox.reduceTabOverflow" = true
"security.insecure_connection_text.enabled" = true

[simplerentfox]
repository = "https://github.com/MiguelRAvila/SimplerentFox"
[simplerentfox.files]
linux = [
    "Linux/userChrome__WithURLBar.css",
    "Linux/userContent.cs"
]
windows = [
    "Windows/userChrome__WithURLBar.css",
    "Windows/userContent.css"
]
[simplerentfox.config]
"layers.acceleration.force-enabled" = true
"gfx.webrender.all" = true
"svg.context-properties.content.enabled" = true
```

code:
```go
package main

import (
	"io/ioutil"
	"net/url"
	"os"
	"testing"

	"github.com/pelletier/go-toml"
)

func main() {
	themesList := ReadThemesList()
}

func ReadFileBytes(filepath string) []byte {
	file, err := os.Open(filepath)
	if err != nil {
		panic(err)
	}
	defer file.Close()
	b, err := ioutil.ReadAll(file)
	return b
}

type ThemesList map[string]struct {
	repository string
	files      map[string][]string
	config     map[string]interface{}
}

func ReadThemesList() ThemesList {
	themesList := ThemesList{}
	doc := ReadFileBytes("themes.toml")
	toml.Unmarshal(doc, &themesList)
	return themesList
}
```

**Expected behavior**
`themesList["materialfox"].repository` should be `"https://github.com/muckSponge/MaterialFox"` instead of `""`, for example.

**Versions**
 - go-toml: v1.8.0 (how am I supposed to know which commit is installed?, if it's the latest from the repo when the package was downloaded, I'm using 34de94e6a887dcd421ab7586d76d26ee5ab3d96a)
 - go: 1.14.4
 - operating system: linux/amd64 (under WSL)

**Additional context**
See the [spew.Dump](https://github.com/davecgh/go-spew/spew) output:
```go
(main.ThemesList) (len=2) {
 (string) (len=11) "materialfox": (struct { repository string; files map[string][]string; config map[string]interface {} }) {
  repository: (string) "",
  files: (map[string][]string) <nil>,
  config: (map[string]interface {}) <nil>
 },
 (string) (len=13) "simplerentfox": (struct { repository string; files map[string][]string; config map[string]interface {} }) {
  repository: (string) "",
  files: (map[string][]string) <nil>,
  config: (map[string]interface {}) <nil>
 }
}
```
