### ISSUE TITLE
Unmarshal leads to panic

### ISSUE THREAD

**Issue by chrisquin** [pelletier/go-toml#480]
**Describe the bug**
my `config.toml` includes accidently `[[devices]]` and `[[meters]]` instead of `[[device]]` and `[[meter]]` (note the missing "s"). I expect to get an err, not a kernel panic. Seems that there is something wrong with regex or substrings?

**To Reproduce**
```go
type MeterConfig struct {
	ID       int `json:"id" toml:"id"`
	Register int `json:"register" toml:"register"`
	OldID    int `json:"old_id,omitempty" toml:"-"`
}

type DeviceConfig struct {
	Name       string `toml:"name"`
	SerialPath string `toml:"serial_path"`
	LinkMode   string `toml:"link_mode"`
}

type Config struct {
	Meter  []MeterConfig  `toml:"meter"`
	Device []DeviceConfig `toml:"device"`
	Title  string         `toml:"title"`
}
```

```toml
title = "foo"

[[devices]]
name = "xyz"
serial_path = "/dev/ttyUSB0"
link_mode = "C1"

[[meters]]
id = 12345678
register = 12345

```

```go
func readConfig(path string) (Config, error) {
	wmbusConfig, err := ioutil.ReadFile(path)
	if err != nil {
		return Config{}, err
	}

	config := Config{}
	err = toml.Unmarshal(wmbusConfig, &config)  <--------------------kernel panic
	if err != nil {
		return Config{}, err
	}

	return config, nil
}

```

**Versions**
 - go-toml: v1.8.1
 - go: 1.14
 - operating system: Linux
