### ISSUE TITLE
Ignoring manual changes to toml file

### ISSUE THREAD

**Issue by Integralist** [pelletier/go-toml#514]
Hi 👋🏻 

I have a toml file that I'm decoding into a struct (as per standard usage of this package), and my go program during its lifetime will make in-memory changes to the struct data structure and then encode that back into the file.

This is all fine. Now, the issue I have is that I would like to make a manual change to the toml file (specifically adding new syntax). I still want my program to handle the toml syntax it is aware of (i.e. is defined as struct types in my code), but I want it to ignore the new syntax that I manually added to the file.

For example...

```toml
# here is the syntax that I've defined as struct types in my go program (my real toml is fairly complex IRL)...

foo = "bar"
baz = 123

# the following would have been manually added outside of the program and whenever I'm encoding/decoding, I want this data to be ignored...

[some.thing]
  ["testing_stuff"]
  whatever = { abc = "xyz" }
```

I've found that if I open the file using `os.OpenFile(filename, os.O_RDWR|os.O_CREATE, 0666)` that it will leave alone the content I want ignored (which is great) but in a non-deterministic fashion it will break encoding of the existing data.

Any ideas or help here would be appreciated.
