### ISSUE TITLE
Wrong marshaling map 

### ISSUE THREAD

**Issue by irbgeo** [pelletier/go-toml#836]
When marshaling a nested map an invalid toml file is generated

**Reproduce**
```golang
var testData map[string]any = map[string]any{
	"plugins": map[string]any{
		"io.containerd.grpc.v1.cri": map[string]any{
			"containerd": map[string]any{
				"runtimes": map[string]any{
					"runc": map[string]any{
						"options": map[string]any{
							"SystemdCgroup": true,
						},
						"runtime_type": "io.containerd.runc.v2",
					},
				},
			},
		},
	},
	"version": 2,
}

// v2 "github.com/pelletier/go-toml/v2"
data, _ = v2.Marshal(testData)
fmt.Printf("%s\n", data)
```
**Actual result**
```toml
version = 2

[plugins]
[plugins.'io.containerd.grpc.v1.cri']
[plugins.'io.containerd.grpc.v1.cri'.containerd]
[plugins.'io.containerd.grpc.v1.cri'.containerd.runtimes]
[plugins.'io.containerd.grpc.v1.cri'.containerd.runtimes.runc]
runtime_type = 'io.containerd.runc.v2'

[plugins.'io.containerd.grpc.v1.cri'.containerd.runtimes.runc.options]
SystemdCgroup = true
```

**Expected result**
```toml
version = 2

[plugins]

  [plugins."io.containerd.grpc.v1.cri"]

    [plugins."io.containerd.grpc.v1.cri".containerd]

      [plugins."io.containerd.grpc.v1.cri".containerd.runtimes]

        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          runtime_type = "io.containerd.runc.v2"

          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
            SystemdCgroup = true
```

**Versions**
 - go-toml: 58a592bbf8f9fb134915b26ff12fd369bd3ca846
 - go: version go1.19.4 linux/amd64
 - operating system:  Linux
