### ISSUE TITLE
key is already defined error when key with same key name is used inside a different table

### ISSUE THREAD

**Issue by akhilerm** [pelletier/go-toml#914]
**Describe the bug**
When there are 2 keys with same name, one inside a table and one outside, based on the order of the outer key , the parsing will pass or fail. If the outer key is written immediately after the table, the parsing fails.

**To Reproduce**
Consider the following struct definition
```go
type release struct {
	ProjectName  string                        `toml:"project_name"`
	Previous     string                        `toml:"previous"`
	OverrideDeps map[string]dependencyOverride `toml:"override_deps"`
}

type dependencyOverride struct {
	Previous string `toml:"previous"`
}
```
- If the toml is as follows, the parsing works as expected
```toml
project_name="containerd"
previous="v1.26.4"
[override_deps]
    [override_deps."github.com/containerd/log"]
        previous="github.com/containerd/containerd"
```

- But if the order is changed in the toml file, then parsing fails with error `toml: key previous is already defined`
```toml
project_name="containerd"
[override_deps]
    [override_deps."github.com/containerd/log"]
        previous="github.com/containerd/containerd"
previous="v1.26.4"
```

**Expected behavior**
Irrespective of where the key `previous` is present in the outer table, the parsing should succeed. 

**Versions**
 - go-toml: verified on v2 main branch 358c8d2c2366571f84d7a8ad3419e48b8a271923 and v2.1.0 version
 - go: go1.21.4
 - operating system: linux/amd64`

**Additional context**
Add any other context about the problem here that you think may help to diagnose.

**Comment by pelletier** [comment]
This is a actually a TOML issue. In this format, indentation doesn't mean anything. In your second example, the document looks like this:

```toml
project_name="containerd"
[override_deps]
[override_deps."github.com/containerd/log"]
previous="github.com/containerd/containerd"
previous="v1.26.4"
```

In TOML, all keys defined after a table belong to that table, until end of file or the next table. So in this case, the table `override_deps."github.com/containerd/log"` does indeed have the key `previous` twice.
